### ISSUE TITLE
WAN Too?

### ISSUE THREAD

**Issue by nobicycle** [bmanojlovic/sendsms#2]
Hello Boris,

Being a cheap skate I was wondering whether your prog could get around paying for expensive SMS  internet based services?  If I have an app in the cloud, is there any reason it could not call sendsms to a local machine running smstools? Probably the local machine and cloud machine would be connected by a VPN.

Any reason why this might not work? Are there any issues you envisage?

If it would work, may I suggest a some  php code to allow any  cloud php app to call directly from php.

best wishes

**Comment by bmanojlovic** [comment]
For start, access control is done on smstools side, meaning that if phone number is not whitelisted it will not allow you to send sms to it (this is how i have set it up by the way :) )
"sendms" is very simple code that post to php file, there is nothing smart in there to be honest, and yes you can just call it from curl  and it should work, my program is just a simple way of doing "curl" where it does not exist. So that code in sendsms.php is doing real work of creating sms file for sending SMS, look into that file it should clear confusion.

**Comment by nobicycle** [comment]
thank you.
